services:
  # Frontend
  frontend:
    image: jaimetuyuc/b-frontend-arm:arm
    ports:
      - 3000:80
    env_file:
      - compose-env-variables.env
  # Backend
  backend:
    image: jaimetuyuc/b-backend-arm:arm
    ports:
      - 4000:4000
    env_file:
      - compose-env-variables.env
  # Services of DB (Database)
  postgres:
   image: postgres:14.5
   ports:
     - 9000:5432
   env_file:
      - compose-env-variables.env
   volumes:
     - PGDATA:/var/lib/postgresql/data
     - ./db:/docker-entrypoint-initdb.d
volumes:
  PGDATA: