FROM node:16-alpine3.15 as build

ENV REACT_APP_BACKEND_URL=http://localhost:4000 \
    REACT_APP_API_CURRENCY=789b86b66d976dcd8c7706da

COPY . /opt/app

WORKDIR /opt/app

RUN npm install

RUN npm run build

FROM nginx:1.23.2-alpine

COPY --from=build /opt/app/build /usr/share/nginx/html