apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pv-claim
  labels:
    app: budget-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-database
  template:
    metadata:
      labels:
        app: budget-database
    spec:
      volumes:
      - name: pg-persistent-storage
        persistentVolumeClaim:
          claimName: pg-pv-claim
      - name: pg-cm-storage
        configMap:
          name: pg-configmap
      containers:
      - name: budget-database
        image: postgres:14.5
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-secrets-ag
                key: password
          - name: PGDATA
            value: "/var/lib/postgresql/data/pgdata"
        resources:
          limits:
            memory: "512Mi"
            cpu: "512m"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pg-persistent-storage
          mountPath: /var/lib/postgresql/data
        - name: pg-cm-storage
          mountPath: /docker-entrypoint-initdb.d
---
apiVersion: v1
kind: Service
metadata:
  name: budget-database-service
spec:
  type: ClusterIP
  selector:
    app: budget-database
  ports:
  - port: 9000
    targetPort: 5432
