FROM node:18.12-alpine3.15

ENV PORT=4000 \
    FRONT_END_URL=http://localhost:3000 \
    HOST=172.17.0.2 \
    USER_DB=postgres \
    DB_PORT=5432 \
    PASSWORD=123456 \
    DATABASE=postgres \
    SECRET_KEY_JWT= \
    EMAIL_API_KEY=

COPY . /opt/app

WORKDIR /opt/app

RUN npm install 

CMD ["npm", "start"]